services:
  web:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: budget-user
      POSTGRES_PASSWORD: budget-password
      POSTGRES_DB: budget-track-db
    ports:
      - "8081:5432"
    healthcheck:
      test: [ "CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
