services:
  web:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:17
    volumes:
        - db-data:/var/lib/postgresql/data
    restart: always
    env_file: "dev.env"
    ports:
      - "8081:5432"
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
