services:
  db:
    image: postgres:17
    volumes:
        - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: "dev.env"
    ports:
      - "8081:5432"
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
