// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        uuid.UUID
	Name      string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transaction struct {
	ID              uuid.UUID
	Description     string
	AccountID       uuid.UUID
	UserID          uuid.UUID
	ValueInCents    int32
	TransactionDate pgtype.Date
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UserAccount struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
