// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Name      string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type Transaction struct {
	ID              uuid.UUID
	Description     string
	AccountID       uuid.UUID
	UserID          uuid.UUID
	ValueInCents    int32
	TransactionDate time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UserAccount struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
