// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        uuid.UUID
	Name      string
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Transaction struct {
	ID              uuid.UUID
	Description     string
	AccountID       uuid.UUID
	ValueInCents    int32
	TransactionDate pgtype.Date
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type UserAccount struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
