// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transactions.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const transactionInsert = `-- name: TransactionInsert :exec

INSERT INTO transaction (id, description, account_id, value_in_cents, transaction_date)
VALUES (generate_uuid_v4, $1, $2, $3, $4)
`

type TransactionInsertParams struct {
	Description     string
	AccountID       uuid.UUID
	ValueInCents    int32
	TransactionDate time.Time
}

func (q *Queries) TransactionInsert(ctx context.Context, arg TransactionInsertParams) error {
	_, err := q.db.ExecContext(ctx, transactionInsert,
		arg.Description,
		arg.AccountID,
		arg.ValueInCents,
		arg.TransactionDate,
	)
	return err
}
